# 设置目标系统
set(CMAKE_SYSTEM_NAME Windows)

# 打印信息
message(STATUS "TOOLCHAIN_PATH: ${TOOLCHAIN_PATH}")
message(STATUS "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
message(STATUS "CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")

# 指定交叉编译器
set(CMAKE_C_COMPILER ${TOOLCHAIN_PATH}/bin/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-gcc.exe)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}/bin/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-g++.exe)

# 指定工具链sysroot目录
# 通常可以这样查询：${TOOLCHAIN_PATH}/bin/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-gcc -print-sysroot
# set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_PATH}/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32)

# 只在工具链目录中查找库和头文件
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
